### ISSUE TITLE
Bash highlighting incorrectly highlights numbers in long strings

### ISSUE THREAD

**Issue by stuartlangridge** [isagalaev/highlight.js#1062]
For example,

``````
```bash
97e143e762a1d1e3abac9eba33a59a7a6b9f319a7063cd47e406678c379fc683
```
``````

incorrectly produces the following HTML:

```
<pre class="highlighted">
    <code class="language-bash hljs">
        <span class="hljs-number">97</span>
        e143e762a1d1e3abac9eba33a59a7a6b9f319a7063
        <span class="hljs-built_in">cd</span>
        47e406678c379
        <span class="hljs-built_in">fc</span>
        683
    </code>
</pre>
```

highlighting the initial "97" as a number, and so on. This may be an inevitable consequence of regexp-based parsing, but importantly there seems to be no way of disabling it. 

Obviously it would be possible to not declare that the code is bash (which it only arguably is in this case: it's the output of a `sha256sum` command) but lines such as

``````
```bash
sha256sum elementaryos-0.3.2-stable-i386.20151209.iso
```
``````

also have a similar problem; the 0.3, the 2, and the 20151209 in the above line are also highlighted as numbers, which looks strange.

**Comment by isagalaev** [comment]
That was fixed a while ago in #983 and has been released in December. An update is due! :-)

**Comment by stuartlangridge** [comment]
Oops. Thank you :-)

**Comment by mDuo13** [comment]
I'm still seeing something like this even after updating to version 9.11. Specifically, the letters "cd" are highlighted as a command even though they're part of a long token string. For example:

```bash
export TOKEN=6909009598052333cd79b455d5479d88a27afe20e5623df7632780acec22430
```

The letters `cd` get highlighted even though they appear as part of a token string, not a command:

```
<code class="hljs bash expanded" title="Double-click to expand/collapse">
  <span class="hljs-built_in">export</span>
 TOKEN=6909009598052333<span class="hljs-built_in">cd</span>79b455d5479d88a27afe20e5623df7632780acec22430
</code>
```

**Comment by isagalaev** [comment]
Indeed…
